# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_worked', models.FloatField()),
                ('employee_id', models.PositiveIntegerField()),
                ('job_group', models.CharField(max_length=100)),
                ('report_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payroll_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveIntegerField()),
                ('period', models.CharField(max_length=25)),
                ('period_start_date_ts', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['employee_id', 'period_start_date_ts'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.PositiveIntegerField()),
            ],
        ),
    ]
